# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imageload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.CharField(max_length=50)),
                ('imageurl', models.URLField()),
                ('imagetext', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteid', models.IntegerField()),
                ('sitename', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='imageload',
            name='sites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.sites'),
        ),
    ]
